language: r
r:
 - release
 - devel
 - oldrel

sudo: false
cache: packages

r_github_packages:
  - HenrikBengtsson/matrixStats@develop
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
